 const validEmailDomains = [
    'gmail.com',
    'outlook.com',
    'yahoo.com',
    'hotmail.com',
    'icloud.com',
    'protonmail.com',
    'aol.com',
    'live.com',
    'msn.com',
    'me.com',
    'mac.com',
    'googlemail.com',
    'ymail.com',
    'rocketmail.com',
    'fastmail.com',
    'zoho.com',
    'mail.com',
    'gmx.com',
    'web.de',
    't-online.de',
    'freenet.de',
    'arcor.de',
    'tiscali.it',
    'libero.it',
    'virgilio.it',
    'orange.fr',
    'laposte.net',
    'free.fr',
    'wanadoo.fr',
    'sfr.fr',
    'rediffmail.com',
    'indiatimes.com',
    'sify.com',
    'vsnl.net',
    'airtelmail.com',
    'bsnl.in',
    'mtnl.net.in'
];

const validProviders = [
    // Popular UPI Apps
    'googlepay',
    'gpay',
    'phonepe',
    'paytm',
    'amazonpay',
    'bhim',
    'freecharge',
    'mobikwik',
    'airtelpay',
    'jio',
    'jiofin',
    'jiopay',
    
    // Major Banks
    'sbi',
    'oksbi',
    'hdfc',
    'okhdfc',
    'icici',
    'okicici',
    'axis',
    'okaxis',
    'pnb',
    'okpnb',
    'canara',
    'union',
    'okunion',
    'kotak',
    'okkotak',
    'yes',
    'okyes',
    'ybl',
    'okybl',
    'idfc',
    'okidfc',
    'rbl',
    'okrbl',
    'bob',
    'okbob',
    'iob',
    'okiob',
    'uco',
    'okuco',
    'psb',
    'okpsb',
    'centralbank',
    'okcentralbank',
    'indianbank',
    'okindianbank',
    
    // Finance Companies
    'bajaj',
    'bajajfinserv',
    'bajajpay',
    'okbajaj',
    'bajajfinance',
    'okbajajfinance',
    'bajajfin',
    'okbajajfin',
    
    // Other Popular Banks
    'fino',
    'okfino',
    'payzapp',
    'okpayzapp',
    'sbiunipay',
    'oksbiunipay',
    'hdfcpayzapp',
    'okhdfcpayzapp',
    'icicipay',
    'okicicipay',
    'axisbank',
    'okaxisbank',
    'pnbbank',
    'okpnbbank',
    'canarabank',
    'unionbank',
    'okunionbank',
    'kotakbank',
    'okkotakbank',
    'yesbank',
    'okyesbank',
    'idfcbank',
    'okidfcbank',
    'rblbank',
    'okrblbank',
    
    // More Banks
    'bankofbaroda',
    'okbankofbaroda',
    'bankofindia',
    'okbankofindia',
    'centralbankofindia',
    'okcentralbankofindia',
    'indianoverseasbank',
    'okindianoverseasbank',
    'punjabandsindbank',
    'okpunjabandsindbank',
    'uco',
    'okuco',
    'puduvai',
    'okpuduvai',
    'puduvaiurban',
    'okpuduvaiurban',
    'puduvaiurbancoop',
    'okpuduvaiurbancoop',
    'puduvaiurbancooperative',
    'okpuduvaiurbancooperative',
    'puduvaiurbancooperativebank',
    'okpuduvaiurbancooperativebank',
    
    // Regional Banks
    'karnataka',
    'okkarnataka',
    'andhra',
    'okandhra',
    'telangana',
    'oktelangana',
    'tamilnadu',
    'oktamilnadu',
    'kerala',
    'okkerala',
    'maharashtra',
    'okmaharashtra',
    'gujarat',
    'okgujarat',
    'rajasthan',
    'okrajasthan',
    'punjab',
    'okpunjab',
    'haryana',
    'okharyana',
    'delhi',
    'okdelhi',
    'up',
    'okup',
    'bihar',
    'okbihar',
    'jharkhand',
    'okjharkhand',
    'odisha',
    'okodisha',
    'westbengal',
    'okwestbengal',
    'assam',
    'okassam',
    'northeast',
    'oknortheast',
    
    // Generic UPI
    'upi',
    'okupi',
    'pay',
    'okpay',
    'money',
    'okmoney',
    'bank',
    'okbank',
    'transfer',
    'oktransfer',
    'send',
    'oksend',
    'receive',
    'okreceive',
    
    // Additional Popular
    'cred',
    'okcred',
    'groww',
    'okgroww',
    'zerodha',
    'okzerodha',
    'upstox',
    'okupstox',
    'angelone',
    'okangelone',
    'icicidirect',
    'okicicidirect',
    'hdfcsec',
    'okhdfcsec',
    'kotaksec',
    'okkotaksec',
    'axissec',
    'okaxissec',
    'sbinet',
    'oksbinet',
    'pnbnet',
    'okpnbnet',
    'unionnet',
    'okunionnet',
    'canaranet',
    'okcanaranet',
    'yesnet',
    'okyesnet',
    'idfcnet',
    'okidfcnet',
    'rblnet',
    'okrblnet',
    'bobnet',
    'okbobnet',
    'iobnet',
    'okiobnet',
    'uconet',
    'okuconet',
    'psbnet',
    'okpsbnet',
    'centralbanknet',
    'okcentralbanknet',
    'indianbanknet',
    'okindianbanknet'
];

export const validateEmailDomain = (email) => {
    if (!email || !email.includes('@')) {
        return false;
    }
    const domain = email.split('@')[1]?.trim();
    return validEmailDomains.includes(domain);
};




export const validateUpiProvider = (upiId) => {
    if (!upiId || !upiId.includes('@')) {
        return false;
    }
    
    const provider = upiId.split('@')[1]?.toLowerCase().trim();
    
    return validProviders.includes(provider);
};