export const AUTH_DATA = "AUTH_DATA";
export const USER_LIST = "USER_LIST";
export const ADDRESS_LIST = "ADDRESS_LIST";
export const ADDRESS_BY_LIST = "ADDRESS_BY_LIST"


export const DASHBOARD_LENGTH = "DASHBOARD_LENGTH"
export const MONTHLY_ORDER_LIST = "MONTHLY_ORDER_LIST"


export const CATEGORY_LIST = "CATEGORY_LIST"
export const SUB_CATEGORY_LIST = "SUB_CATEGORY_LIST"
export const PRODUCT_LIST = "PRODUCT_LIST"
export const PRODUCT_GET_BY_LIST = "PRODUCT_GET_BY_LIST"
export const SYNC_PRODUCT_LIST = "SYNC_PRODUCT_LIST"
export const FAQ_LIST = "FAQ_LIST"
export const FAQ_GET_BY_LIST = "FAQ_GET_BY_LIST"
export const CONTACT_LIST = "CONTACT_LIST"
export const CONTACT_GET_BY_LIST = "CONTACT_GET_BY_LIST"

export const TERM_GET_BY_LIST = "TERM_GET_BY_LIST"
export const TERM_LIST = "TERM_LIST"
export const VENDOR_GET_BY_LIST = "VENDOR_GET_BY_LIST"
export const VENDOR_LIST = "VENDOR_LIST"
export const CART_LIST = "CART_LIST"

export const ORDER_BY_LIST = "ORDER_BY_LIST"
export const ORDER_LIST = "ORDER_LIST"

export const BANNER_GET_BY_LIST = "BANNER_GET_BY_LIST"
export const BANNER_LIST = "BANNER_LIST"

export const STOCK_LIST = "STOCK_LIST"

export const RECEIVABLE_GET_BY_LIST = "RECEIVABLE_GET_BY_LIST"
export const RECEIVABLE_LIST = "RECEIVABLE_LIST"

export const LOGS_LIST = "LOGS_LIST"


export const SYNC_LIST = "SYNC_LIST"
export const SYNC_GET_BY_LIST = "SYNC_GET_BY_LIST"


export const LEDGER_LIST = "LEDGER_LIST"
export const LEDGER_GET_BY_LIST = "LEDGER_GET_BY_LIST"

export const PAYMENT_LIST = "PAYMENT_LIST"
export const PAYMENT_GET_BY_LIST = "PAYMENT_GET_BY_LIST"

export const FETCH_TALLY_DATA = "FETCH_TALLY_DATA"
export const UPDATE_TALLY = "UPDATE_TALLY"







